"""ascend_transpiler — Python-to-Ascend-C transpiler."""
from ascend_transpiler.dsl.decorators import (
    ascend_op,
    tile,
    relu,
    sqrt,
    exp,
    log,
    abs,
    tanh,
    sigmoid,
    sin,
    cos,
    floor,
    ceil,
    round,
    sign,
    reciprocal,
    gelu,
    silu,
    leaky_relu,
    rsqrt,
    logical_not,
    maximum,
    minimum,
    logical_and,
    logical_or,
    add_relu,
    sub_relu,
    mul_cast,
    maxs,
    mins,
    ands,
    ors,
    shift_left,
    shift_right,
    axpy,
    mul_add_dst,
    fused_mul_add,
    mul_add_relu,
    compare,
    compares,
    select,
    duplicate,
    create_vec_index,
    clamp,
    cast,
    matmul,
    reduce_sum,
    reduce_max,
    reduce_min,
    reduce_mean,
)
from ascend_transpiler.dsl.types import (
    Tensor,
    float16,
    float32,
    float64,
    bfloat16,
    int8,
    int16,
    int32,
    int64,
    uint8,
    uint16,
    uint32,
    mxfp8,
    mxfp4,
    hif8,
)
from ascend_transpiler.transpiler import Transpiler

__all__ = [
    # Decorators
    "ascend_op", "tile",
    # Primitives — unary
    "relu", "sqrt", "exp", "log", "abs", "tanh", "sigmoid",
    "sin", "cos", "floor", "ceil", "round", "sign", "reciprocal",
    "gelu", "silu", "leaky_relu", "rsqrt", "logical_not",
    # Primitives — binary elementwise tensor×tensor
    "maximum", "minimum", "logical_and", "logical_or",
    "add_relu", "sub_relu", "mul_cast",
    # Primitives — scalar binary (tensor×scalar)
    "maxs", "mins", "ands", "ors", "shift_left", "shift_right",
    # Primitives — 3-input fused / special
    "axpy", "mul_add_dst", "fused_mul_add", "mul_add_relu",
    "compare", "compares", "select",
    "duplicate", "create_vec_index", "clamp",
    # Special
    "cast", "matmul",
    "reduce_sum", "reduce_max", "reduce_min", "reduce_mean",
    # Types
    "Tensor",
    "float16", "float32", "float64", "bfloat16",
    "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32",
    "mxfp8", "mxfp4", "hif8",
    # Programmatic API
    "Transpiler",
]
